// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  // this getter dynamically selects the correct Firebase configuration
  // based on the platform the Flutter app is running on.
  static FirebaseOptions get currentPlatform {
    // checks if the app is running on a web platform.
    if (kIsWeb) {
      return web; // if it's web, return the Firebase configuration for web.
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAnKzRFutyAdi-yL3_U_wrGmixDVecCew0",
    authDomain: "serene-flutter-project.firebaseapp.com",
    projectId: "serene-flutter-project",
    storageBucket: "serene-flutter-project.appspot.com",
    messagingSenderId: "877241651124",
    appId: "1:877241651124:web:f7071ec4b426a9eb192ce1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhrNpErpZgH5mMO6y95RUfaG7aFAOhf8',
    appId: '1:877241651124:android:49db2cb99cab98d6192ce1',
    messagingSenderId: '877241651124',
    projectId: 'serene-flutter-project',
    storageBucket: 'serene-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWG5IOZDkmQ800sQ_ioupR2__MvuFLBI',
    appId: '1:877241651124:ios:ff5793bd10baf1c1192ce1',
    messagingSenderId: '877241651124',
    projectId: 'serene-flutter-project',
    storageBucket: 'serene-flutter-project.appspot.com',
    iosBundleId: 'com.empowherhacks.serene',
  );
}
